echo "We are trying this practical from linux EC2"
echo "We are from batch-25 and learning git/gihub"
echo "nilam good famlsdkfl git conflict"
echo " we are in branch -nilam "
echo " hello its commit in my feature branch"
echo " create conflict in  woh r u"